version: '3.3'

services:
  docker-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - /data/mysql
  agenda-api-app:
    image: agenda-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    volumes:
      - /data/app
  
  