server:
  port: 8080  
spring:
  application:
    name: agenda-api
    
#DATA
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/agenda
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#jacskon
  jackson:
    default-property-inclusion: non-null
    
    
    

 